### ISSUE TITLE
use DOI instead of uuid for archive lookup

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl-zenodo-storage#3]

**Comment by zaneselvans** [comment]
I think the basic ID we have to work with is probably the "record ID" right? From which the DOI can be constructed given the Zenodo prefix?  At least that's how it looked on the sandbox site.

**Comment by ptvirgo** [comment]
If / when this gets re prioritized: it is acceptable to automatically create and store the DOIs to a script-specific saved state.

**Comment by zschira** [comment]
Done in the new [archiver repo](https://github.com/catalyst-cooperative/pudl-archiver)
