### ISSUE TITLE
Create archiver for FERC Form 2

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-zenodo-storage#30]
We have a real scraper for FERC Form 2, now we need a way to convert that into an archive on Zenodo.

This one is a little bit complicated, since there are now 3 different data formats, they overlap in time, and the earlier data is split into two files per year.

* [ ] **1991-1999:** Data is available in DAT format, split into 2 files per year (A-M, and N-Z)
* [ ] **1996-2021Q2:** Data is available in DBF format, one file per year.
* [ ] **2021-present:** Data is available in XBRL format via an RSS feed that has one filing per feed item.

**Comment by zschira** [comment]
Done in the new [archiver repo](https://github.com/catalyst-cooperative/pudl-archiver)
