### ISSUE TITLE
Create Archiver for FERC Form 6

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-zenodo-storage#31]
We now have a scraper for the FERC Form 6, but need to be able to archive the data on Zenodo. There are two separate sources with non-overlapping coverage:

* [ ] **2000-2020:** DBF files, one per year.
* [ ] **2021-present:** XBRL published in an RSS feed, with one filing per feed item.

**Comment by zschira** [comment]
Done in the new [archiver repo](https://github.com/catalyst-cooperative/pudl-archiver)
