### ISSUE TITLE
Create archiver for FERC Form 60

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-zenodo-storage#32]
We have a scraper for the FERC Form 60, but we need an archiver to go with it:

* [ ] **2006-2020**: DBF zipfiles, one per year
* [ ] **2021-present:** XBRL data published via an RSS feed, one filing per feed item.

**Comment by zschira** [comment]
Done in the new [archiver repo](https://github.com/catalyst-cooperative/pudl-archiver)
