### ISSUE TITLE
Update FERC Form 1 archiver to work with DBF + XBRL

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-zenodo-storage#34]
The FERC Form 1 is now published as a combination of historical VisualFoxPro DBF databases, and XBRL data, and we need a way to archive them together as a single dataset.

* [ ] **1994-2021Q2:** DBF zipfiles, one per year.
* [ ] **2021-present:** XBRL data published via RSS feed, one filing per feed item.

**Comment by zschira** [comment]
Done in the new [archiver repo](https://github.com/catalyst-cooperative/pudl-archiver)
